{% set name = "itkwidgets" %}
{% set version = "0.32.5" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a3429e3d05649b14d666b17482280fe0370d6fd2efaafacfcb8eb0e86162b8b

build:
  number: 0
  skip: true  # [win32 or py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - jupyter
  run:
    - python
    - colorcet
    - itk >=5.1.0
    - ipydatawidgets >=4.0.1
    - ipywidgets >=7.5.0
    - ipympl
    - numpy
    - six
    - zstandard

test:
  imports:
    - itkwidgets

about:
  home: https://github.com/InsightSoftwareConsortium/itkwidgets
  license: Apache 2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Interactive Jupyter widgets to visualize images in 2D and 3D
  doc_url: https://github.com/InsightSoftwareConsortium/itkwidgets
  dev_url: https://github.com/InsightSoftwareConsortium/itkwidgets

extra:
  recipe-maintainers:
    - thewtex
    - SylvainCorlay
