{% set name = "itkwidgets" %}
{% set version = "0.26.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87b9aab5d31102186b8edfd905132e78aeeaf519dc58af1b9635583ed622854d

build:
  number: 0
  skip: true  # [win32 or py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - jupyter
  run:
    - python
    - colorcet
    - itk >=5.0.1
    - ipydatawidgets >=4.0.1
    - ipywidgets >=7.5.0
    - ipympl
    - numpy
    - scipy
    - six
    - zstandard

test:
  imports:
    - itkwidgets

about:
  home: https://github.com/InsightSoftwareConsortium/itkwidgets
  license: Apache 2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Interactive Jupyter widgets to visualize images in 2D and 3D
  doc_url: https://github.com/InsightSoftwareConsortium/itkwidgets
  dev_url: https://github.com/InsightSoftwareConsortium/itkwidgets

extra:
  recipe-maintainers:
    - hadim
    - thewtex
    - SylvainCorlay
